### ISSUE TITLE
Try both IPv4 and IPv6 for all (?) relays

### ISSUE THREAD

**Issue by pastly** [oftc/TorIPScanner#1]
Right now we connect directly to a hardcoded IP of one of OFTC's servers.

We *should* try connecting to both irc4.oftc.net and irc6.oftc.net.

When doing this, we need to be careful we don't do it back-to-back, as the IRC will complain at you that you're reconnecting too quickly.

**Comment by dwfreed** [comment]
The scanner should take our servers.yaml as input (path to the file in the scanner's config), as well as a list of plain and ssl ports.  Make an intersection of the list of server IP/port pairs with the relay's exit policies, and then if anything matches, pick a match at random and test it, for both IPv4 and IPv6.  You don't have to worry about reconnecting too fast, as the test in the ircd looks at same source IP, so a different protocol won't trigger it.

Something like this: (python-like psuedo-code)

```
results = []
for relay in relays:
    servers = servers_intersect_exit_policy(relay, IPv4) # List[Tuple[str, int]]
    if servers:
        result = test(random.choice(servers))
        if result:
            results.append(result)

    if relay.IPv6:
        servers = servers_intersect_exit_policy(relay, IPv6)
        if servers:
            result = test(random.choice(servers))
            if result:
                results.append(result)
```
